### ISSUE TITLE
Spicetify Manager won't detect spicetify installed through winget

### ISSUE THREAD

**Issue by sergio-faraldo** [AdotBdot/SpicetifyManager#3]
# Issue
Spicetify Manager is unable to detect a winget installed instance of spicetify.
## Description
Spicetify looks for Spicetify in appdata\Local, if spicetify is installed through winget, it is installed in the following path:

`%localappdata%\microsoft\winget\packages\Spicetify.Spicetify_Microsoft.Winget.Source_8wekyb3d8bbwe`

I am unsure as to whether this path can change from installation to installation, but the folder should always start with Spicetify.Spicetify, since that's the name of the winget package.

The config is stored in the same folder as other types of installations:
```
> spicetify -c
C:\Users\<username>\AppData\Roaming\spicetify\config-xpui.ini
``` 

### Adding a config file to change these paths
Adding the option to change where Spicetify Manager looks for spicetify would solve not only this, but other weird edge-cases, where someone decides to install spicetify somewhere else. Something like this would do the trick:

spicetify-manager.conf

```
{
  spicetify-exe-path: "%LOCALAPPDATA%\microsoft\winget\packages\Spicetify.Spicetify*\"
  spicetify-conf-folder: "%APPDATA%\spicetify\"
}
``` 
or:
```
{
  spicetify-exe-path: ["%LOCALAPPDATA%\spicetify\",
    "%LOCALAPPDATA%\microsoft\winget\packages\Spicetify.Spicetify*\"]
  spicetify-conf-folder: ["%APPDATA%\spicetify\"]
}
``` 

Syntax may be different, as Window's classic backslashes can cause problems. A custom config file could be a solution to that, like taking the first option and going for a simple:
```
spicetify-exe-path=%LOCALAPPDATA%\spicetify\
spicetify-conf-folder=%APPDATA%\spicetify\
```
By default it could have the regular paths and the user could be prompted to change them if spicetify is not detected.
### Call spicetify directly
Another possible solution is to try to call spicetify direcly, if it's in the path variables it should work, and running `spicetify -c` returns the config file, which, minus the "config-xpui.ini" part at the end, provides the config folder:
```
> spicetify -c
C:\Users\<username>\AppData\Roaming\spicetify\config-xpui.ini
``` 
Using PowerShell's get-command and .Path it is also possible to know where spicetify is installed, in case it is necessary:
```
> (get-command spicetify).Path
C:\Users\<username>\AppData\Local\Microsoft\WinGet\Packages\Spicetify.Spicetify_Microsoft.Winget.Source_8wekyb3d8bbwe\spicetify.exe
``` 

## Logs
```
Detecting Spicetify...
Directory C:\Users\<username>\AppData\Local\spicetify\ does not exist.
File C:\Users\<username>\AppData\Local\spicetify\spicetify.exe does not exist.
``` 
## Notes
In all text copied, my username on my PC was changed to `<username>`. The logs show my actual username in that spot.

**Comment by AdotBdot** [comment]
Thanks for letting me know.
I wanted to avoid using config file but, as you said, it may be the simplest and the most universal solution.
The patch will be released in sparse time. I think that adding some sort of configuration file and trying to call spicetify directly will do the trick.

**Comment by AdotBdot** [comment]
Will you provide me what is your input for spicetify in Path under Environment Variables?

**Comment by sergio-faraldo** [comment]
C:\Users\<username>\AppData\Local\Microsoft\WinGet\Packages\Spicetify.Spicetify_Microsoft.Winget.Source_8wekyb3d8bbwe

(the entry was automatically created by winget, it seems, I didn't create it myself)

**Comment by AdotBdot** [comment]
A new release has been published. If everything works fine I will close the issue.

**Comment by sergio-faraldo** [comment]
Seems to be working fine now, I'll close the issue.
Thanks :)

**Comment by KeiBoogie** [comment]
I'm having this same issue
